from tools.github_tool import get_trending_repos
from tools.weather_tool import get_weather


def executor_agent(plan: dict):
    """
    Executes the steps generated by planner agent
    """

    results = {}

    for step in plan["steps"]:

        tool = step["tool"]
        params = step.get("params", {})

        if tool == "github":
            results["github"] = get_trending_repos()

        elif tool == "weather":
            city = params.get("location", "Delhi")
            results["weather"] = get_weather(city)

    return results
